/** SEAMUN I 2027 schedules by committee group (from schedules.pdf). */
(function (global) {
  global.SEAMUNSchedule = {
    group1: {
      id: "group1",
      label: "Group 1",
      committees: ["UNHRC", "DISEC", "Press Corps"],
      debateTotals: { day1: "6 hours", day2: "4 hours 45 minutes" },
      days: [
        {
          title: "Day 1 — Friday, January 16, 2027",
          items: [
            { time: "7:30", activity: "Arrival & Registration" },
            { time: "8:30", activity: "Opening Ceremony" },
            { time: "9:15", activity: "Break & Photo Ops" },
            { time: "9:45", activity: "Icebreakers" },
            { time: "10:00", activity: "Committee Session 1 — Motion Focused" },
            { time: "11:00", activity: "Lunch (Eat)" },
            { time: "11:30", activity: "Lunch (Socialise)" },
            { time: "12:00", activity: "Committee Session 2 — Resolution Writing" },
            { time: "14:30", activity: "Break & Photo Ops — Resolutions Due" },
            { time: "15:00", activity: "Committee Session 3 — Voting Procedures" },
            { time: "16:30", activity: "Feedback Sessions & Delegate Departure" },
            { time: "17:00", activity: "Chair + SMT Departure" },
          ],
        },
        {
          title: "Day 2 — Saturday, January 17, 2027",
          items: [
            { time: "7:30", activity: "Arrival" },
            { time: "8:30", activity: "Registration & Photo Ops" },
            { time: "9:00", activity: "Committee Session 1 — Motion Focused" },
            { time: "10:00", activity: "Break" },
            { time: "10:30", activity: "Committee Session 2 — Motions & Resolution Writing" },
            { time: "12:00", activity: "Lunch (Socialise)" },
            { time: "12:30", activity: "Lunch (Eat)" },
            { time: "13:00", activity: "Committee Session 3 — Resolution Writing" },
            { time: "14:30", activity: "Break — Resolutions Due" },
            { time: "15:00", activity: "Committee Session 4 — Voting Procedures" },
            { time: "16:00", activity: "Feedback & Break" },
            { time: "16:30", activity: "Closing Ceremony" },
            { time: "17:30", activity: "Photo Ops & Chair + Delegate Departure" },
            { time: "18:00", activity: "SMT Departure" },
          ],
        },
      ],
    },
    group2: {
      id: "group2",
      label: "Group 2",
      committees: ["WHO", "UN Women", "UNSC"],
      debateTotals: { day1: "6 hours", day2: "4 hours 45 minutes" },
      days: [
        {
          title: "Day 1 — Friday, January 16, 2027",
          items: [
            { time: "7:30", activity: "Arrival & Registration" },
            { time: "8:30", activity: "Opening Ceremony" },
            { time: "9:15", activity: "Break & Photo Ops" },
            { time: "9:45", activity: "Icebreakers" },
            { time: "10:00", activity: "Committee Session 1 — Motion Focused" },
            { time: "11:00", activity: "Lunch (Socialise)" },
            { time: "11:30", activity: "Lunch (Eat)" },
            { time: "12:30", activity: "Committee Session 2 — Resolution Writing" },
            { time: "14:30", activity: "Break & Photo Ops — Resolutions Due" },
            { time: "15:00", activity: "Committee Session 3 — Voting Procedures" },
            { time: "16:30", activity: "Feedback Sessions & Delegate Departure" },
            { time: "17:00", activity: "Chair + SMT Departure" },
          ],
        },
        {
          title: "Day 2 — Saturday, January 17, 2027",
          items: [
            { time: "7:30", activity: "Arrival" },
            { time: "8:30", activity: "Registration & Photo Ops" },
            { time: "9:00", activity: "Committee Session 1 — Motion Focused" },
            { time: "10:00", activity: "Break" },
            { time: "10:30", activity: "Committee Session 2 — Motions & Resolution Writing" },
            { time: "11:30", activity: "Lunch (Eat)" },
            { time: "12:00", activity: "Lunch (Socialise)" },
            { time: "12:30", activity: "Committee Session 3 — Resolution Writing" },
            { time: "14:30", activity: "Break — Resolutions Due" },
            { time: "15:00", activity: "Committee Session 4 — Voting Procedures" },
            { time: "16:00", activity: "Feedback & Break" },
            { time: "16:30", activity: "Closing Ceremony" },
            { time: "17:30", activity: "Photo Ops & Chair + Delegate Departure" },
            { time: "18:00", activity: "SMT Departure" },
          ],
        },
      ],
    },
    group3: {
      id: "group3",
      label: "Group 3",
      committees: ["ECOSOC", "UNODC", "Interpol", "FWC"],
      debateTotals: { day1: "6 hours", day2: "4 hours 45 minutes" },
      days: [
        {
          title: "Day 1 — Friday, January 16, 2027",
          items: [
            { time: "7:30", activity: "Arrival & Registration" },
            { time: "8:30", activity: "Opening Ceremony" },
            { time: "9:15", activity: "Break & Photo Ops" },
            { time: "9:45", activity: "Icebreakers" },
            { time: "10:00", activity: "Committee Session 1 — Motion Focused" },
            { time: "11:30", activity: "Lunch (Socialise)" },
            { time: "12:00", activity: "Lunch (Eat)" },
            { time: "13:00", activity: "Committee Session 2 — Resolution Writing" },
            { time: "14:30", activity: "Break & Photo Ops — Resolutions Due" },
            { time: "15:00", activity: "Committee Session 3 — Voting Procedures" },
            { time: "16:30", activity: "Feedback Sessions & Delegate Departure" },
            { time: "17:00", activity: "Chair + SMT Departure" },
          ],
        },
        {
          title: "Day 2 — Saturday, January 17, 2027",
          items: [
            { time: "7:30", activity: "Arrival" },
            { time: "8:30", activity: "Registration & Photo Ops" },
            { time: "9:00", activity: "Committee Session 1 — Motion Focused" },
            { time: "10:00", activity: "Break" },
            { time: "10:30", activity: "Committee Session 2 — Motions & Resolution Writing" },
            { time: "11:30", activity: "Lunch (Socialise)" },
            { time: "12:00", activity: "Lunch (Eat)" },
            { time: "12:30", activity: "Committee Session 3 — Resolution Writing" },
            { time: "14:30", activity: "Break — Resolutions Due" },
            { time: "15:00", activity: "Committee Session 4 — Voting Procedures" },
            { time: "16:00", activity: "Feedback & Break" },
            { time: "16:30", activity: "Closing Ceremony" },
            { time: "17:30", activity: "Photo Ops & Chair + Delegate Departure" },
            { time: "18:00", activity: "SMT Departure" },
          ],
        },
      ],
    },
  };
})(typeof window !== "undefined" ? window : this);
